import midi
import pygame
from pychord import Chord

# takes the chords generated by markov chain, and plays song with it 
def play_song(chords):

    pygame.init()

    for chord in chords: 
        chord_data = Chord(chord)
        midi_data = chord_data.to_midi()
                # initialize pygame

    # load the MIDI data into pygame
    pygame.mixer.music.load(pygame.mixer.music.pygame._midi.make_file(midi_data))

    # play the MIDI data
    pygame.mixer.music.play()

    # wait for the MIDI data to finish playing
    while pygame.mixer.music.get_busy():
        pygame.time.wait(1000)



